-- Explanation skins for Concept 1 "What AI Is"
-- Launch set: generic/EN, generic/HI, elderly/HI, farmer/HI, student/EN
-- All non-safety-critical. human_reviewed = TRUE for launch.

INSERT INTO explanation_skins (
  skin_id, concept_id, status, locale, persona,
  literacy_level, is_safety_critical, human_reviewed,
  day1_hook, day2_reveal, day3_practice,
  day4_retrieval_q, day4_acceptable_ans,
  day5_check_prompt, one_liner,
  primary_analogy_id,
  primary_format, reading_required, max_words_per_screen, font_size_class,
  completion_message, completion_style,
  family_bridge_summary, wa_headline, wa_body, wa_cta
) VALUES

-- 1. generic / en
('c01_generic_en', 'c01', 'published', 'en', 'generic',
 'medium', FALSE, TRUE,
 'Imagine someone who has read every book, newspaper, and website ever written — but has never left the room. That is AI.',
 'AI learns by reading enormous amounts of text written by humans. It finds patterns in what it has read and uses those to respond. It has no experiences, no common sense, and no feelings. When it gives you an answer, it is making its best guess based on patterns — not because it truly understands.',
 'Try this: Ask an AI assistant "What is the weather in my village today?" and notice what happens. Does it actually know? What does its answer tell you about what AI can and cannot do?',
 'What is one thing AI has never done, no matter how much it has read?',
 ARRAY['It has never lived / had experiences', 'It does not know your local situation', 'It cannot sense or feel', 'It has no real understanding', 'It has never stepped outside'],
 'In your own words, finish this sentence: "I will trust AI when _____ but I will verify before _____."\n\nThere is no wrong answer. This is about building your own rule.',
 'AI is a very well-read student who has never lived.',
 'a_understand_elder_en',
 'text', FALSE, 18, 'md',
 'You now understand what AI is — and is not. That is the foundation of everything.',
 'quiet_glow',
 'AI has read more than any human — but it has never lived. So for real decisions, a real person still matters more.',
 'What is AI, really?',
 'AI learns from text — it has never lived. Adhyan explains what that means for you.',
 'Open Adhyan'),

-- 2. generic / hi
('c01_generic_hi', 'c01', 'published', 'hi', 'generic',
 'medium', FALSE, TRUE,
 'सोचिए कोई ऐसा व्यक्ति जिसने दुनिया की हर किताब, हर अखबार, हर वेबसाइट पढ़ी हो — पर कमरे से बाहर कभी नहीं निकला। यही है AI।',
 'AI बहुत सारे लिखे हुए शब्दों को पढ़कर सीखता है। वह उन पैटर्न को पहचानता है और उनसे जवाब बनाता है। उसके पास न कोई अनुभव है, न समझ, न भावना। जब वह जवाब देता है तो यह उसका "सबसे अच्छा अनुमान" होता है — सच्ची समझ नहीं।',
 'यह करके देखें: किसी AI से पूछें "आज मेरे गाँव में मौसम कैसा है?" और ध्यान दें क्या होता है। क्या उसे सच में पता है? इससे क्या पता चलता है?',
 'AI ने चाहे कितना भी पढ़ा हो — एक काम वह कभी नहीं कर सकता। वह क्या है?',
 ARRAY['AI ने कभी जीवन नहीं जिया', 'उसे आपकी स्थानीय स्थिति नहीं पता', 'वह महसूस नहीं कर सकता', 'उसकी कोई असली समझ नहीं', 'वह कभी बाहर नहीं निकला'],
 'अपने शब्दों में यह वाक्य पूरा करें: "मैं AI पर भरोसा करूँगा/करूँगी जब _____ लेकिन _____ से पहले जाँच ज़रूर करूँगा/करूँगी।"',
 'AI एक बहुत पढ़ा-लिखा छात्र है जिसने कभी जीवन नहीं जिया।',
 'a_understand_elder_en',
 'text', FALSE, 15, 'md',
 'आपने समझ लिया AI क्या है — और क्या नहीं है। यही सब कुछ सीखने की नींव है।',
 'quiet_glow',
 'AI ने इंसानों से ज़्यादा पढ़ा है — पर उसने कभी जीवन नहीं जिया। असली फ़ैसलों के लिए असली इंसान ज़रूरी है।',
 'AI असल में क्या है?',
 'AI लिखे हुए शब्दों से सीखता है — उसने कभी जीवन नहीं जिया। Adhyan बताता है इसका क्या मतलब है आपके लिए।',
 'Adhyan खोलें'),

-- 3. elderly / hi
('c01_elderly_hi', 'c01', 'published', 'hi', 'elderly',
 'low', FALSE, TRUE,
 'मान लीजिए कोई है जिसने पूरे शहर के सारे अखबार पढ़े हैं — पर बाज़ार कभी नहीं गया, डॉक्टर के पास कभी नहीं गया, किसी से कभी नहीं मिला। AI ऐसा ही है।',
 'AI बहुत सारा लिखा हुआ पढ़कर सीखता है। वह जवाब देता है, पर उसे आपकी ज़िंदगी नहीं पता। उसे आपके मोहल्ले की खबर नहीं, आपकी तकलीफ नहीं पता, आपके परिवार को नहीं जानता। इसीलिए बड़े फ़ैसलों के लिए — जैसे दवा, पैसे, या ज़मीन — हमेशा किसी जानकार इंसान से भी पूछें।',
 'यह करके देखें: किसी AI से पूछें "मुझे यह दवाई लेनी चाहिए?" और देखें वह क्या कहता है। फिर किसी डॉक्टर से पूछें। फ़र्क़ नोट करें।',
 'AI ने लाखों किताबें पढ़ी हैं — फिर भी एक काम वह नहीं कर सकता। वह क्या है?',
 ARRAY['आपकी ज़िंदगी नहीं जी सकता', 'आपकी तकलीफ महसूस नहीं कर सकता', 'आपके गाँव को नहीं जानता', 'कभी बाहर नहीं निकला', 'असली दुनिया का अनुभव नहीं है'],
 'एक बात बताइए: जब आप AI से पूछेंगे और जब किसी इंसान से पूछेंगे — दोनों में क्या फ़र्क़ होगा?',
 'AI बहुत पढ़ा-लिखा है — पर उसने ज़िंदगी नहीं जी।',
 'a_understand_elder_en',
 'audio', FALSE, 12, 'xl',
 'शाबाश। आप समझ गए AI क्या है। यही सबसे ज़रूरी बात है।',
 'quiet_glow',
 'AI ने बहुत कुछ पढ़ा है पर ज़िंदगी नहीं जी। बड़े फ़ैसलों में किसी भरोसेमंद इंसान से ज़रूर पूछें।',
 'AI क्या है — सरल भाषा में',
 'AI बहुत पढ़ा-लिखा है पर उसने ज़िंदगी नहीं जी। Adhyan में जानें इसका क्या मतलब है।',
 'Adhyan खोलें'),

-- 4. farmer / hi
('c01_farmer_hi', 'c01', 'published', 'hi', 'farmer',
 'medium', FALSE, TRUE,
 'सोचिए बाज़ार में एक दलाल है जिसने हज़ारों खेतों के भाव पढ़े हैं — पर खुद कभी खेत में नहीं गया, मिट्टी नहीं छुई, बारिश नहीं देखी। AI ऐसा ही है।',
 'AI बहुत सारी जानकारी पढ़कर सीखता है। वह MSP बता सकता है, मौसम का अनुमान दे सकता है, योजनाओं की जानकारी दे सकता है — लेकिन आपके खेत की ज़मीन, आपके ज़िले की स्थिति, इस साल की बारिश — यह उसे नहीं पता। इसीलिए AI एक शुरुआत है, आखिरी जवाब नहीं।',
 'यह करके देखें: AI से पूछें "इस महीने मेरे खेत में क्या बोना चाहिए?" और देखें वह क्या कहता है। फिर किसी स्थानीय कृषि सलाहकार से पूछें।',
 'AI हज़ारों खेतों की जानकारी रखता है — पर एक काम वह नहीं कर सकता। वह क्या है?',
 ARRAY['आपके खेत की मिट्टी नहीं जानता', 'इस साल का मौसम नहीं देखा', 'आपके गाँव की स्थिति नहीं पता', 'ज़मीन पर कभी नहीं गया', 'स्थानीय अनुभव नहीं है'],
 'अपने शब्दों में बताइए: खेती के किस काम में AI मदद कर सकता है, और किसमें नहीं?',
 'AI बाज़ार का भाव जानता है — आपके खेत की मिट्टी नहीं।',
 'a_understand_farmer_hi',
 'audio', FALSE, 15, 'lg',
 'बढ़िया। आपने सीखा AI क्या है — अब आप इसका सही इस्तेमाल कर सकते हैं।',
 'quiet_glow',
 'AI बहुत कुछ जानता है पर आपके खेत की मिट्टी नहीं। स्थानीय फ़ैसलों के लिए स्थानीय इंसान से भी पूछें।',
 'किसान के लिए AI क्या है?',
 'AI हज़ारों खेतों की जानकारी रखता है — पर आपकी मिट्टी नहीं जानता। Adhyan में जानें।',
 'Adhyan खोलें'),

-- 5. student / en
('c01_student_en', 'c01', 'published', 'en', 'student',
 'high', FALSE, TRUE,
 'Imagine a classmate who has read every textbook, every Wikipedia article, every social media post ever written — but has never attended a single class discussion, never failed a test, never felt nervous before an exam. That is AI.',
 'AI is a statistical pattern-matcher. It predicts the most likely next word or sentence based on everything it has been trained on. It does not reason, understand, or care about truth. It is very good at sounding right — which is exactly what makes it dangerous if you use it without thinking.',
 'Open any AI chatbot and ask it: "What did I score in my last exam?" Then ask: "What should I study tonight?" Compare the two answers. What does this tell you about what AI knows — and does not know?',
 'Why does AI sometimes sound very confident even when it is wrong?',
 ARRAY['Because it predicts likely-sounding text', 'It matches patterns without understanding truth', 'It has no way to know what it does not know', 'It optimises for fluency not accuracy', 'Pattern matching does not include a confidence check'],
 'Think of one decision you have to make this week — college, career, study plan. How could AI help you think it through, and where would you need to check with a real person? Write it out.',
 'AI sounds like it knows — but it is guessing, very fast.',
 'a_understand_student_en',
 'text', FALSE, 20, 'md',
 'You understand what AI actually is. That makes you smarter than most adults using it right now.',
 'warm_pulse',
 'AI sounds confident but it is pattern-matching, not thinking. Understanding this is a real advantage.',
 'What AI really is — for students',
 'AI sounds like it knows everything. Here is what is actually happening inside. Adhyan explains.',
 'Open Adhyan');
