-- Explanation skins for c06–c10 (generic/EN only for launch)
-- c06 safety_critical=TRUE → human_reviewed=TRUE
-- c10 safety_critical=TRUE → human_reviewed=TRUE
-- c07, c08, c09 not safety-critical

INSERT INTO explanation_skins (
  skin_id, concept_id, status, locale, persona,
  literacy_level, is_safety_critical, human_reviewed,
  day1_hook, day2_reveal, day3_practice,
  day4_retrieval_q, day4_acceptable_ans,
  day5_check_prompt, one_liner,
  primary_format, reading_required, max_words_per_screen, font_size_class,
  completion_message, completion_style,
  wa_headline, wa_body, wa_cta
) VALUES

-- ─────────────────────────────────────────────
-- c06 — Job Scam Signs (safety_critical)
-- ─────────────────────────────────────────────

('c06_generic_en', 'c06', 'published', 'en', 'generic',
 'medium', TRUE, TRUE,
 'A WhatsApp message arrives: "Earn ₹30,000/month liking YouTube videos. No experience needed. Work from home. Registration fee ₹500 only. Join today — offer expires at midnight." Ten thousand people received this same message. It was generated by AI in seconds. Most of them lost their ₹500. Some lost much more.',
 'AI-generated fake job offers are now personalised, fluent, and sent at scale. They are hard to spot because they look professional.\n\nFive red flags that never change:\n1. Salary too high for too little work\n2. No interview, no skill check required\n3. Asks for registration, security, or training fee upfront\n4. Contact only via WhatsApp — no office address\n5. Urgency: "offer expires tonight"\n\nRule: any job that charges you money is not a job. It is a scam.',
 'Look at the job offer message above again. Identify every red flag you can find. How many of the five are present?',
 'What are the five red flags of a fake job offer?',
 ARRAY['Too-high salary for simple work', 'No interview required', 'Registration or fee required upfront', 'WhatsApp-only contact with no office', 'Urgent deadline or expiry'],
 'Write down: the next time you or a family member sees a job offer on WhatsApp, what is the first thing you will check?',
 'Any job that pays too much for too little is a trap.',
 'text', FALSE, 16, 'md',
 'You can now spot a fake job offer. Share this with anyone in your family who is job hunting — it could save them real money.',
 'warm_pulse',
 'Spot the fake job offer',
 'AI-generated job scams look real. Here are the 5 signs — and the one rule. Share with Adhyan.',
 'Share with family'),

-- ─────────────────────────────────────────────
-- c07 — Asking AI Better
-- ─────────────────────────────────────────────

('c07_generic_en', 'c07', 'published', 'en', 'generic',
 'medium', FALSE, TRUE,
 'Ask AI "help me write a letter" and you get a generic template. Ask "help me write a formal complaint letter to my bank''s branch manager in Mumbai, explaining that my debit card was blocked unfairly and I want it restored within 3 days" — and you get something you can actually send. The difference is context.',
 'AI is a helper who knows nothing about you unless you tell them. The more context you give, the better the answer.\n\nFive things that improve any prompt:\n1. Who you are (your situation, your role)\n2. What you actually want (specific goal)\n3. What you have tried (so it does not repeat)\n4. Where you are (city, state, context)\n5. What format you need (letter, list, explanation, short answer)\n\nYou do not need to be formal. Write as you would talk to a helpful friend.',
 'Take something you actually need right now — a letter, a question, a complaint. Write the vague version. Then rewrite it with all five context elements added. Compare the two answers AI gives.',
 'What is the most important thing you can add to a question to get a better answer from AI?',
 ARRAY['Context about your situation', 'Specific details about what you need', 'Who you are and what you are trying to do', 'Your location and circumstances', 'What format or length you want'],
 'Write one question you have been wanting to ask AI. Now rewrite it with full context. Which version would you rather receive an answer to?',
 'The quality of your question decides the quality of the answer.',
 'text', FALSE, 18, 'md',
 'You now know how to get 10x more useful answers from AI. This skill compounds every time you use it.',
 'quiet_glow',
 'Better questions, better answers',
 'Most people ask AI vague questions and get vague answers. Learn the 5-part formula with Adhyan.',
 'Open Adhyan'),

-- ─────────────────────────────────────────────
-- c08 — AI for Your Daily Work
-- ─────────────────────────────────────────────

('c08_generic_en', 'c08', 'published', 'en', 'generic',
 'medium', FALSE, TRUE,
 'You do not need to be a tech expert to use AI for real work. In the next 10 minutes, you could use AI to: draft a complaint letter to your landlord, translate a government notice from English to Hindi, calculate simple loan interest, or write a polite WhatsApp message to a difficult customer.',
 'Practical uses that work today:\n- Write letters (complaint, application, formal request)\n- Translate documents or notices\n- Summarise long text into key points\n- Check eligibility for government schemes (ask: "Am I eligible for PM Awas Yojana if I earn ₹X in [state]?")\n- Draft customer messages for your shop\n- Explain medical instructions in simple language\n- Calculate EMI, interest, discounts\n\nRemember: verify anything about health, legal matters, or large sums of money.',
 'Choose one real task from your life right now. Use AI to do it. Then reflect: did it save you time? Did you need to verify anything? What would you use it for next?',
 'Name two practical tasks from your daily life where AI could save you time today.',
 ARRAY['Writing a complaint or application letter', 'Translating a document', 'Checking government scheme eligibility', 'Writing customer messages', 'Calculating interest or EMI', 'Summarising a long notice'],
 'What is the one thing you will use AI for this week — and what will you double-check before acting on the result?',
 'AI can draft, translate, explain, and summarise — in your language.',
 'text', FALSE, 18, 'md',
 'You have completed the practical skills module. AI is now a real tool in your hands.',
 'quiet_glow',
 'AI for real daily tasks',
 'From writing letters to translating notices — AI works in your language. Adhyan shows you how.',
 'Open Adhyan'),

-- ─────────────────────────────────────────────
-- c09 — When Not to Trust AI
-- ─────────────────────────────────────────────

('c09_generic_en', 'c09', 'published', 'en', 'generic',
 'medium', FALSE, TRUE,
 'A man asked AI whether his chest pain could be anxiety. It said yes, gave him a detailed, confident explanation. He postponed seeing a doctor for three weeks. The diagnosis was a minor cardiac event. AI was not wrong about anxiety being possible — it was wrong about that being the full picture for this specific man.',
 'Three domains where AI alone is never enough:\n\n1. MEDICAL — AI can explain conditions, but cannot examine you, know your history, or take responsibility. Always end with a real doctor.\n\n2. LEGAL — AI knows general law but not your specific contract, your local court, or your circumstances. Always consult a legal aid office or qualified lawyer.\n\n3. FINANCIAL — AI can explain how products work, but cannot assess your full situation, your risk, or your tax implications. Always verify with a certified advisor or official portal.\n\nFor everything else: AI is a great starting point. For these three: it is only a starting point.',
 'Think of a health, legal, or financial question you (or someone in your family) have had recently. How would you use AI as a starting point — and where would you go to actually confirm the answer?',
 'Name the three domains where AI should never be your final answer.',
 ARRAY['Health / medical decisions', 'Legal matters', 'Financial decisions', 'Medicine and law and money', 'Doctor lawyer financial advisor'],
 'Finish this sentence for each domain: "For medical questions I will use AI to _____ but confirm with _____."',
 'Medical, legal, and financial decisions need a human expert.',
 'text', FALSE, 18, 'md',
 'You know exactly where AI helps and where it is not enough. This boundary protects you and your family.',
 'quiet_glow',
 'Know AI''s limits',
 'AI is a great start for health, legal, and financial questions — but never the final answer. Adhyan explains.',
 'Open Adhyan'),

-- ─────────────────────────────────────────────
-- c10 — Scam Literacy (safety_critical)
-- ─────────────────────────────────────────────

('c10_generic_en', 'c10', 'published', 'en', 'generic',
 'medium', TRUE, TRUE,
 'Every scam in history — before and after AI — uses the same two levers: make the target afraid, then demand instant action before they can think. The technology changes. The formula does not.',
 'The formula: Fear + Urgency = Action before thought.\n\nExamples:\n- "Your account will be blocked in 24 hours" (fear) "Call now" (urgency)\n- "Your son is in trouble" (fear) "Send money immediately" (urgency)\n- "You have won ₹25,000 — claim before midnight" (fear of missing out) "Click now" (urgency)\n\nAI makes the messages more convincing, more personalised, and sent at scale. But the formula is identical.\n\nThe counter: one rule, always. When you feel fear AND urgency at the same time — STOP. Call someone you trust. Do not act until you have done that.',
 'Look at any message you received this week — from any source. Can you identify: (1) the fear element, (2) the urgency element? If both are present, it is almost certainly a scam.',
 'What are the two levers every scam uses — and what is the one rule to counter them?',
 ARRAY['Fear plus urgency equals action before thought', 'Make afraid then demand immediate action', 'Create panic then prevent thinking', 'Fear and urgency together — stop and call someone'],
 'In your own words: what will you tell your family the next time they feel scared and rushed by a message or call?',
 'Fear plus urgency is the scammer''s formula — slow down.',
 'text', FALSE, 18, 'md',
 'You have completed all 10 concepts. You can now spot, avoid, and explain every major AI-powered scam. Share this with your family.',
 'warm_pulse',
 'The scammer''s formula',
 'Every scam uses fear + urgency. Learn the one rule that stops any scam cold. Adhyan.',
 'Share with family');
